Repository JacquelineMG/midterm, pull requests merged in 2023-07, with the labels that each got.

#2 Header, form, and list basic HTML & CSS
  styles/funsie-list.scss
  styles/header.scss
  styles/layout.scss
  styles/main.scss
  styles/new-funsie.scss
  views/index.ejs
Labels: enhancement

#3 Navbar merge
  styles/nav.scss
  views/index.ejs
Labels: enhancement

#7 Load data from database and show funsies list on frontend
  package-lock.json
  public/scripts/app.js
  views/index.ejs
Labels: enhancement

#8 Filtering by category, sorting by recency & completion
  public/scripts/app.js
  views/index.ejs
Labels: enhancement

#9 Database
  planning/Funsies.drawio.png
  planning/funsies-ERD.drawio.png
  public/scripts/app.js
  public/scripts/users.js
  routes/items.js
  views/index.ejs
Labels: enhancement

#10 Drop down form
  public/scripts/form.js
  styles/new-funsie.scss
  views/index.ejs
Labels: enhancement

#11 page re-renders when add new item & sorting function fixed
  public/scripts/app.js
  routes/data-helpers.js
  routes/items.js
Labels: enhancement

#14 Show completed toggle filters by completion status & css changes for select categories
  public/scripts/app.js
  styles/funsie-list.scss
Labels: enhancement

#18 Completion route
  public/scripts/app.js
  routes/data-helpers.js
  routes/items.js
Labels: enhancement

#19 bug fix - move filtering into renderPage function
  public/scripts/app.js
Labels: bug

#22 Bug fix: category change on category pages
  public/scripts/app.js
Labels: bug

#23 bug fix: change event listener for delete to listen for form submission
  public/scripts/app.js
  routes/items.js
Labels: bug

#24 Update the README with project details
  README.md
  docs/all-form-down.png
  docs/all-form-up.png
  docs/buy.png
  docs/eat.png
  docs/read.png
  docs/watch.png
Labels: documentation
